package com.runechronicle;
import java.awt.*;import java.util.*;import javax.swing.*;import javax.swing.border.*;import net.runelite.client.game.ItemManager;import net.runelite.client.util.AsyncBufferedImage;
final class BreakdownDialog{
 private static final Color BG=new Color(8,10,13),CARD=new Color(17,20,25),LINE=new Color(47,53,62),GOLD=new Color(242,187,59),WHITE=new Color(242,245,248),MUTED=new Color(151,160,173),GREEN=new Color(83,207,137);
 static void show(Component owner,String kind,RuneChroniclePlugin.Summary s,ItemManager items){JDialog d=new JDialog(SwingUtilities.getWindowAncestor(owner),title(kind),Dialog.ModalityType.MODELESS);d.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);JPanel root=new JPanel();root.setLayout(new BoxLayout(root,BoxLayout.Y_AXIS));root.setBackground(BG);root.setBorder(new EmptyBorder(22,24,24,24));JLabel h=lab(title(kind),24,WHITE,Font.BOLD);root.add(h);root.add(lab(sub(kind,s),10,MUTED,Font.PLAIN));root.add(Box.createVerticalStrut(16));if("LOOT".equals(kind))loot(root,s,items);else if("XP".equals(kind))map(root,s.skillXp,"XP");else if("BOSSES".equals(kind))map(root,s.bossCounts,"defeated");else map(root,s.killCounts,"defeated");JScrollPane sc=new JScrollPane(root);sc.setBorder(null);sc.getViewport().setBackground(BG);sc.getVerticalScrollBar().setUnitIncrement(18);d.setContentPane(sc);d.setSize(610,650);d.setMinimumSize(new Dimension(500,450));d.setLocationRelativeTo(owner);d.getRootPane().registerKeyboardAction(e->d.dispose(),KeyStroke.getKeyStroke("ESCAPE"),JComponent.WHEN_IN_FOCUSED_WINDOW);d.setVisible(true);}
 private static void loot(JPanel root,RuneChroniclePlugin.Summary s,ItemManager items){Map<String,java.util.List<ChronicleStore.Event>> by=new LinkedHashMap<>();for(ChronicleStore.Event e:s.events)if("LOOT".equals(e.type))by.computeIfAbsent(e.source==null||e.source.isEmpty()?"Other loot":e.source,k->new ArrayList<>()).add(e);if(by.isEmpty()){root.add(empty("No recorded loot in this period."));return;}for(Map.Entry<String,java.util.List<ChronicleStore.Event>> g:by.entrySet()){long total=0;for(ChronicleStore.Event e:g.getValue())total+=e.value;root.add(section(g.getKey()+"  ·  "+RuneChroniclePlugin.gp(total)+" gp"));for(ChronicleStore.Event e:g.getValue())root.add(lootRow(e,items));}}
 private static JPanel lootRow(ChronicleStore.Event e,ItemManager items){JPanel p=card(new BorderLayout(12,0));JLabel art=new JLabel();art.setPreferredSize(new Dimension(44,44));try{AsyncBufferedImage im=items.getImage(e.itemId,Math.max(1,e.quantity),e.quantity>1);if(im!=null)im.addTo(art);}catch(Exception ignored){}p.add(art,BorderLayout.WEST);JPanel m=new JPanel();m.setOpaque(false);m.setLayout(new BoxLayout(m,BoxLayout.Y_AXIS));m.add(lab(e.title+" ×"+Math.max(1,e.quantity),12,WHITE,Font.BOLD));long unit=e.quantity>0?e.value/e.quantity:e.value;m.add(lab(RuneChroniclePlugin.gp(unit)+" gp ea  ·  "+RuneChroniclePlugin.gp(e.value)+" gp total",9,GOLD,Font.PLAIN));m.add(lab("High Alch: "+RuneChroniclePlugin.gp(e.haValue)+" gp total",9,MUTED,Font.PLAIN));p.add(m);return p;}
 private static void map(JPanel root,Map<String,Long> m,String suffix){if(m.isEmpty()){root.add(empty("Nothing recorded in this period."));return;}m.entrySet().stream().sorted((a,b)->Long.compare(b.getValue(),a.getValue())).forEach(e->{JPanel p=card(new BorderLayout());p.add(lab(e.getKey(),12,WHITE,Font.BOLD),BorderLayout.WEST);p.add(lab("XP".equals(suffix)?"+"+String.format("%,d",e.getValue())+" XP":"×"+e.getValue(),11,"XP".equals(suffix)?GREEN:GOLD,Font.BOLD),BorderLayout.EAST);root.add(p);});}
 private static String title(String k){return "LOOT".equals(k)?"Loot Breakdown":"XP".equals(k)?"XP Breakdown":"BOSSES".equals(k)?"Boss Breakdown":"Kill Breakdown";}
 private static String sub(String k,RuneChroniclePlugin.Summary s){if("LOOT".equals(k))return RuneChroniclePlugin.gp(s.lootValue)+" gp total · "+s.lootItems+" items claimed";if("XP".equals(k))return String.format("%,d",s.xp)+" XP earned";if("BOSSES".equals(k))return s.bossKills+" bosses defeated";return s.kills+" monsters defeated";}
 private static JLabel section(String x){JLabel l=lab(x,11,GOLD,Font.BOLD);l.setBorder(new EmptyBorder(16,2,7,2));return l;}private static JPanel card(LayoutManager l){JPanel p=new JPanel(l);p.setBackground(CARD);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(2,0,2,0),BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(11,12,11,12))));p.setMaximumSize(new Dimension(Integer.MAX_VALUE,72));return p;}private static JPanel empty(String x){JPanel p=card(new BorderLayout());p.add(lab(x,10,MUTED,Font.PLAIN));return p;}private static JLabel lab(String s,int z,Color c,int st){JLabel l=new JLabel(s);l.setForeground(c);l.setFont(new Font("SansSerif",st,z));return l;}
}
