package com.runechronicle;
import java.awt.*;import javax.swing.*;import javax.swing.border.*;
final class ChronicleSettingsDialog extends JDialog{
 ChronicleSettingsDialog(RuneChroniclePlugin p){setTitle("RuneChronicle · Settings");setModal(false);setSize(450,650);setLocationRelativeTo(null);JPanel root=new JPanel();root.setLayout(new BoxLayout(root,BoxLayout.Y_AXIS));root.setBackground(RuneChroniclePanel.BG);root.setBorder(new EmptyBorder(20,22,22,22));
  root.add(text("RUNECHRONICLE",20,RuneChroniclePanel.WHITE,Font.BOLD));root.add(text("Journal controls · RuneChronicle 0.7.1",10,RuneChroniclePanel.GOLD,Font.BOLD));root.add(gap(14));
  root.add(section("WHAT TO REMEMBER"));JCheckBox loot=check("Claimed loot & rewards",p.config().logLoot()),kills=check("Monster kills",p.config().logMonsterKills()),bosses=check("Bosses defeated",p.config().logBossKills()),activities=check("Raids, chests, clues & activities",p.config().logActivities()),milestones=check("Quests, Collection Log, pets, PBs & achievements",p.config().logGameMilestones()),deaths=check("Deaths",p.config().logDeaths());for(JCheckBox c:new JCheckBox[]{loot,kills,bosses,activities,milestones,deaths})root.add(c);
  root.add(section("RECAP"));JCheckBox gameRecap=check("In-game RECAP control",p.config().showGameRecapButton()),recap=check("Sidebar OPEN RECAP button",p.config().showRecapEntry());root.add(gameRecap);root.add(recap);
  root.add(section("LOOT FILTER"));root.add(label("MINIMUM GE VALUE"));JSpinner ge=new JSpinner(new SpinnerNumberModel(p.config().minimumGeValue(),0,2000000000,50000));root.add(ge);root.add(label("MINIMUM HIGH ALCH VALUE"));JSpinner ha=new JSpinner(new SpinnerNumberModel(p.config().minimumHaValue(),0,2000000000,50000));root.add(ha);JCheckBox stack=check("Use whole stack value",p.config().useStackValue());root.add(stack);root.add(label("QUALIFY WHEN"));JComboBox<RuneChronicleConfig.LootValueRule> rule=new JComboBox<>(RuneChronicleConfig.LootValueRule.values());rule.setSelectedItem(p.config().lootValueRule());root.add(rule);
  root.add(section("YOUR CHRONICLE DATA"));JPanel data=new JPanel(new GridLayout(1,3,6,0));data.setOpaque(false);JButton export=btn("EXPORT"),imp=btn("IMPORT"),reset=btn("RESET");export.addActionListener(e->p.exportChronicle(this));imp.addActionListener(e->p.importChronicle(this));reset.addActionListener(e->p.resetChronicle(this));data.add(export);data.add(imp);data.add(reset);root.add(data);JLabel local=text("Local-first: RuneChronicle does not upload your journal to a server.",9,RuneChroniclePanel.MUTED,Font.PLAIN);local.setBorder(new EmptyBorder(7,0,5,0));root.add(local);
  JLabel artwork=text("<html><body style='width:380px'><b>External artwork:</b> NPC names are sent to the OSRS Wiki only to retrieve monster/boss images.<br>Your RSN, account identifier, Chronicle history, drops, credentials, and login/session data are not sent.</body></html>",9,RuneChroniclePanel.MUTED,Font.PLAIN);artwork.setBorder(new EmptyBorder(0,0,12,0));root.add(artwork);
  JPanel buttons=new JPanel(new GridLayout(1,2,8,0));buttons.setOpaque(false);JButton everything=btn("RECORD EVERYTHING"),save=btn("SAVE SETTINGS");everything.addActionListener(e->{ge.setValue(0);ha.setValue(0);loot.setSelected(true);kills.setSelected(true);bosses.setSelected(true);activities.setSelected(true);milestones.setSelected(true);deaths.setSelected(true);stack.setSelected(true);rule.setSelectedItem(RuneChronicleConfig.LootValueRule.GE_OR_HA);});save.addActionListener(e->{set(p,"logLoot",loot.isSelected());set(p,"logMonsterKills",kills.isSelected());set(p,"logBossKills",bosses.isSelected());set(p,"logActivities",activities.isSelected());set(p,"logGameMilestones",milestones.isSelected());set(p,"logDeaths",deaths.isSelected());set(p,"showRecapEntry",recap.isSelected());set(p,"showGameRecapButton",gameRecap.isSelected());set(p,"useStackValue",stack.isSelected());set(p,"minimumGeValue",ge.getValue());set(p,"minimumHaValue",ha.getValue());set(p,"lootValueRule",((RuneChronicleConfig.LootValueRule)rule.getSelectedItem()).name());p.refresh();dispose();});buttons.add(everything);buttons.add(save);root.add(buttons);
  JScrollPane sc=new JScrollPane(root);sc.setBorder(null);sc.getViewport().setBackground(RuneChroniclePanel.BG);sc.getVerticalScrollBar().setUnitIncrement(16);setContentPane(sc);}
 private static Component gap(int n){return Box.createVerticalStrut(n);}private static JButton btn(String s){JButton b=new JButton(s);b.setFocusable(false);b.setFont(new Font("SansSerif",Font.BOLD,9));return b;}private static JCheckBox check(String s,boolean v){JCheckBox c=new JCheckBox(s,v);c.setOpaque(false);c.setForeground(RuneChroniclePanel.WHITE);c.setFont(new Font("SansSerif",Font.PLAIN,11));return c;}private static JLabel section(String s){JLabel l=text(s,9,RuneChroniclePanel.GOLD,Font.BOLD);l.setBorder(new EmptyBorder(15,0,7,0));return l;}private static JLabel label(String s){JLabel l=text(s,8,RuneChroniclePanel.MUTED,Font.BOLD);l.setBorder(new EmptyBorder(8,0,4,0));return l;}private static JLabel text(String s,int z,Color c,int style){JLabel l=new JLabel(s);l.setForeground(c);l.setFont(new Font("SansSerif",style,z));return l;}private static void set(RuneChroniclePlugin p,String k,Object v){p.configManager().setConfiguration("runechronicle",k,v);}
}