package com.runechronicle;
import java.awt.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.List;import javax.swing.*;import javax.swing.event.*;import net.runelite.client.game.ItemManager;import net.runelite.client.util.AsyncBufferedImage;
final class DropHistoryDialog extends JDialog{
 private final RuneChroniclePlugin plugin;private final ItemManager items;private final JTextField search=new JTextField();private final DefaultListModel<RuneChroniclePlugin.ItemChoice> model=new DefaultListModel<>();private final JList<RuneChroniclePlugin.ItemChoice> list=new JList<>(model);private final JPanel results=new JPanel();
 DropHistoryDialog(RuneChroniclePlugin p,ItemManager i){plugin=p;items=i;setTitle("RuneChronicle — Drop History");setModal(false);setSize(650,570);setLocationRelativeTo(null);setDefaultCloseOperation(DISPOSE_ON_CLOSE);JPanel root=new JPanel(new BorderLayout(10,10));root.setBorder(BorderFactory.createEmptyBorder(14,14,14,14));JPanel top=new JPanel(new BorderLayout(8,8));top.add(new JLabel("Search any Old School RuneScape item"),BorderLayout.NORTH);search.setToolTipText("Type part of an item name, e.g. fir for Fire cape");top.add(search);root.add(top,BorderLayout.NORTH);list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);list.setPreferredSize(new Dimension(220,400));root.add(new JScrollPane(list),BorderLayout.WEST);results.setLayout(new BoxLayout(results,BoxLayout.Y_AXIS));root.add(new JScrollPane(results));setContentPane(root);search.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){filter();}public void removeUpdate(DocumentEvent e){filter();}public void changedUpdate(DocumentEvent e){filter();}});list.addListSelectionListener(e->{if(!e.getValueIsAdjusting())render(list.getSelectedValue());});emptyPrompt();}
 private void filter(){String q=search.getText().trim();model.clear();if(q.isEmpty()){emptyPrompt();return;}for(RuneChroniclePlugin.ItemChoice x:plugin.searchItems(q))model.addElement(x);if(!model.isEmpty())list.setSelectedIndex(0);else noMatches(q);}
 private void emptyPrompt(){results.removeAll();JLabel x=new JLabel("<html><b>Find any item in the game</b><br><br>Choose an item to see every time RuneChronicle has recorded you obtaining it.</html>");x.setBorder(BorderFactory.createEmptyBorder(14,10,10,10));results.add(x);results.revalidate();results.repaint();}
 private void noMatches(String q){results.removeAll();JLabel x=new JLabel("<html><b>No OSRS items match “"+esc(q)+"”</b></html>");x.setBorder(BorderFactory.createEmptyBorder(14,10,10,10));results.add(x);results.revalidate();results.repaint();}
 private void render(RuneChroniclePlugin.ItemChoice choice){results.removeAll();if(choice==null){results.revalidate();return;}List<ChronicleStore.Event> es=plugin.lootHistory(choice.id,choice.name);es.sort((a,b)->Long.compare(b.ts,a.ts));JPanel head=new JPanel(new BorderLayout(12,0));JLabel icon=new JLabel();icon.setPreferredSize(new Dimension(48,48));try{AsyncBufferedImage img=items.getImage(choice.id,1,false);img.addTo(icon);}catch(Exception ignored){}head.add(icon,BorderLayout.WEST);long qty=0;for(ChronicleStore.Event e:es)qty+=Math.max(1,e.quantity);JPanel text=new JPanel();text.setLayout(new BoxLayout(text,BoxLayout.Y_AXIS));text.add(new JLabel("<html><b>"+esc(choice.name)+"</b></html>"));text.add(new JLabel(es.isEmpty()?"No recorded drops":es.size()+" recorded drops · "+qty+" total"));head.add(text);results.add(head);results.add(Box.createVerticalStrut(12));if(es.isEmpty()){JLabel none=new JLabel("<html>RuneChronicle has not recorded this account obtaining <b>"+esc(choice.name)+"</b> yet.<br><br>History begins when RuneChronicle is installed; it does not invent earlier drops.</html>");none.setBorder(BorderFactory.createEmptyBorder(8,4,8,4));results.add(none);}else{DateTimeFormatter f=DateTimeFormatter.ofPattern("MMM d, yyyy · h:mm a");for(ChronicleStore.Event e:es){String when=Instant.ofEpochSecond(e.ts).atZone(ZoneId.systemDefault()).format(f);String src=e.source==null||e.source.isEmpty()?"Unknown source":e.source;JLabel row=new JLabel("<html><b>"+when+"</b><br>"+esc(src)+" · ×"+Math.max(1,e.quantity)+" · "+RuneChroniclePlugin.gp(e.value)+" gp</html>");row.setBorder(BorderFactory.createEmptyBorder(7,4,7,4));results.add(row);}}results.revalidate();results.repaint();}
 private static String esc(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
}
