package com.runechronicle;

import java.awt.*;import java.awt.image.BufferedImage;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import javax.swing.*;import javax.swing.border.*;import net.runelite.client.util.AsyncBufferedImage;import net.runelite.client.game.ItemManager;import net.runelite.client.ui.PluginPanel;

final class RuneChroniclePanel extends PluginPanel{
 static final Color BG=new Color(8,10,13),SURFACE=new Color(14,17,21),SURFACE2=new Color(19,23,29),LINE=new Color(43,48,57),GOLD=new Color(238,184,63),WHITE=new Color(241,244,248),MUTED=new Color(142,151,164),GREEN=new Color(82,205,132),RED=new Color(230,100,105),BLUE=new Color(91,158,238),PURPLE=new Color(175,122,239),CYAN=new Color(87,196,205);
 private final RuneChroniclePlugin plugin;private final ItemManager items;private final NpcPortraitService portraits;private final JPanel body=new TrackWidthPanel();private final JLabel status=new JLabel();private final Map<String,JButton>tabs=new LinkedHashMap<>();private String range="SESSION";

 private static final class TrackWidthPanel extends JPanel implements Scrollable {
  @Override public Dimension getPreferredScrollableViewportSize(){return getPreferredSize();}
  @Override public int getScrollableUnitIncrement(Rectangle visibleRect,int orientation,int direction){return 18;}
  @Override public int getScrollableBlockIncrement(Rectangle visibleRect,int orientation,int direction){return Math.max(40,visibleRect.height-40);}
  @Override public boolean getScrollableTracksViewportWidth(){return true;}
  @Override public boolean getScrollableTracksViewportHeight(){return false;}
 }
 RuneChroniclePanel(RuneChroniclePlugin p,ItemManager im,NpcPortraitService np){plugin=p;items=im;portraits=np;setLayout(new BorderLayout());setBackground(BG);add(header(),BorderLayout.NORTH);body.setLayout(new BoxLayout(body,BoxLayout.Y_AXIS));body.setBackground(BG);body.setBorder(new EmptyBorder(8,3,18,3));JScrollPane s=new JScrollPane(body);s.setBorder(null);s.getViewport().setBackground(BG);s.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);s.getVerticalScrollBar().setUnitIncrement(18);add(s,BorderLayout.CENTER);new javax.swing.Timer(1500,e->refresh()).start();refresh();}
 private JComponent header(){JPanel h=new JPanel();h.setLayout(new BoxLayout(h,BoxLayout.Y_AXIS));h.setBackground(BG);h.setBorder(new EmptyBorder(12,6,6,6));
  JPanel top=new JPanel(new BorderLayout(6,0));top.setOpaque(false);JPanel word=new JPanel(new FlowLayout(FlowLayout.LEFT,0,0));word.setOpaque(false);word.add(label("RUNE",14,WHITE,Font.BOLD));word.add(label("CHRONICLE",14,GOLD,Font.BOLD));top.add(word,BorderLayout.WEST);JButton gear=button("⚙");gear.setPreferredSize(new Dimension(28,24));gear.setToolTipText("Journal settings and filters");gear.addActionListener(e->new ChronicleSettingsDialog(plugin).setVisible(true));top.add(gear,BorderLayout.EAST);h.add(top);
  JPanel state=new JPanel(new BorderLayout());state.setOpaque(false);status.setFont(ui(Font.BOLD,9));state.add(status,BorderLayout.WEST);JLabel sub=label("YOUR ADVENTURE, REMEMBERED",7,MUTED,Font.PLAIN);state.add(sub,BorderLayout.EAST);state.setBorder(new EmptyBorder(4,0,10,0));h.add(state);
  JPanel nav=new JPanel(new GridLayout(1,5,3,0));nav.setOpaque(false);for(String x:new String[]{"SESSION","TODAY","WEEK","MONTH","HISTORY"}){JButton z=button(x.substring(0,1)+x.substring(1).toLowerCase());z.setFont(ui(Font.BOLD,9));z.setBorder(new EmptyBorder(7,1,7,1));z.addActionListener(e->{range=x;refresh();});tabs.put(x,z);nav.add(z);}h.add(nav);return h;}
 void refresh(){SwingUtilities.invokeLater(this::render);}
 private void render(){status.setText(plugin.trackingActive()?"● LIVE":"● SYNCING");status.setForeground(plugin.trackingActive()?GREEN:MUTED);for(Map.Entry<String,JButton>e:tabs.entrySet()){boolean on=e.getKey().equals(range);e.getValue().setBackground(on?new Color(52,42,22):SURFACE);e.getValue().setForeground(on?GOLD:MUTED);e.getValue().setBorder(BorderFactory.createLineBorder(on?new Color(121,94,38):LINE));}body.removeAll();RuneChroniclePlugin.Summary s=plugin.summary(range);
  JPanel hero=new JPanel(new BorderLayout());hero.setBackground(new Color(16,19,23));hero.setBorder(BorderFactory.createCompoundBorder(new MatteBorder(1,1,1,1,new Color(50,55,64)),new EmptyBorder(11,9,11,9)));JPanel ht=new JPanel();ht.setOpaque(false);ht.setLayout(new BoxLayout(ht,BoxLayout.Y_AXIS));ht.add(label(range,8,GOLD,Font.BOLD));ht.add(label(RuneChroniclePlugin.format(s.playSeconds)+" adventure",19,WHITE,Font.BOLD));ht.add(label(LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE · MMM d")),9,MUTED,Font.PLAIN));hero.add(ht,BorderLayout.WEST);hero.setMaximumSize(new Dimension(Integer.MAX_VALUE,74));body.add(hero);body.add(Box.createVerticalStrut(6));
  JPanel metrics=new JPanel(new GridLayout(2,2,3,3));metrics.setOpaque(false);metrics.add(metric("XP EARNED",compact(s.xp)+" XP",GREEN,"XP",s));metrics.add(metric("LOOT VALUE",RuneChroniclePlugin.gp(s.lootValue)+" gp",GOLD,"LOOT",s));metrics.add(metric("BOSSES",compact(s.bossKills),RED,"BOSSES",s));metrics.add(metric("MONSTERS",compact(s.kills),WHITE,"KILLS",s));metrics.setMaximumSize(new Dimension(Integer.MAX_VALUE,104));body.add(metrics);
  if(plugin.config().showRecapEntry()){body.add(Box.createVerticalStrut(7));JButton recap=button("OPEN RECAP →");recap.setToolTipText("Open Session, Today, Week and Month recaps");recap.setFont(ui(Font.BOLD,10));recap.setForeground(GOLD);recap.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(121,94,38)),new EmptyBorder(9,8,9,8)));recap.addActionListener(e->plugin.showSessionRecap());recap.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));recap.setAlignmentX(Component.LEFT_ALIGNMENT);body.add(recap);JButton drops=button("DROP HISTORY →");drops.setToolTipText("Find when RuneChronicle recorded an item drop");drops.setFont(ui(Font.BOLD,10));drops.setForeground(GOLD);drops.setBorder(new EmptyBorder(9,8,9,8));drops.addActionListener(e->new DropHistoryDialog(plugin,items).setVisible(true));drops.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));drops.setAlignmentX(Component.LEFT_ALIGNMENT);body.add(Box.createVerticalStrut(5));body.add(drops);}
  if(!s.bossCounts.isEmpty()){body.add(section("BOSSES DEFEATED",GOLD));s.bossCounts.entrySet().stream().sorted((a,b)->Long.compare(b.getValue(),a.getValue())).forEach(e->body.add(bossRow(e.getKey(),e.getValue())));}
  if(!s.skillXp.isEmpty()){body.add(section("PROGRESS",MUTED));s.skillXp.entrySet().stream().sorted((a,b)->Long.compare(b.getValue(),a.getValue())).limit(5).forEach(e->body.add(progress(e.getKey(),e.getValue())));}
  body.add(section("THE CHRONICLE",GOLD));java.util.List<ChronicleStore.Event>v=new ArrayList<>();for(ChronicleStore.Event e:s.events)if(!"SESSION_START".equals(e.type)&&!"SESSION_END".equals(e.type)&&!"XP".equals(e.type))v.add(e);Collections.reverse(v);if(v.isEmpty())body.add(empty());else for(ChronicleStore.Event e:v.subList(0,Math.min(100,v.size())))body.add(eventCard(e));body.revalidate();body.repaint();}
 private JPanel metric(String k,String v,Color accent,String kind,RuneChroniclePlugin.Summary s){JPanel p=surface(new BorderLayout());p.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));p.setToolTipText("Click for "+kind.toLowerCase(Locale.ROOT)+" breakdown");p.setBorder(BorderFactory.createCompoundBorder(new MatteBorder(2,0,0,0,accent),new EmptyBorder(7,4,6,4)));JPanel q=new JPanel();q.setOpaque(false);q.setLayout(new BoxLayout(q,BoxLayout.Y_AXIS));q.add(label(k,7,MUTED,Font.BOLD));q.add(label(v,14,WHITE,Font.BOLD));q.add(label("Breakdown →",7,accent,Font.PLAIN));p.add(q);p.addMouseListener(new java.awt.event.MouseAdapter(){public void mouseClicked(java.awt.event.MouseEvent e){BreakdownDialog.show(p,kind,s,items);}});return p;}
 private JLabel section(String s,Color c){JLabel l=label(s,9,c,Font.BOLD);l.setBorder(new EmptyBorder(17,2,7,2));return l;}
 private JPanel bossRow(String name,long count){JPanel p=surface(new BorderLayout(6,0));JLabel badge=portrait(name,true);p.add(badge,BorderLayout.WEST);JPanel m=new JPanel();m.setOpaque(false);m.setLayout(new BoxLayout(m,BoxLayout.Y_AXIS));m.add(label(name,11,WHITE,Font.BOLD));m.add(label("Tracked this "+range.toLowerCase(),8,MUTED,Font.PLAIN));p.add(m,BorderLayout.CENTER);p.add(label("×"+count,14,GOLD,Font.BOLD),BorderLayout.EAST);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,56));return p;}
 private JPanel progress(String name,long xp){JPanel p=surface(new BorderLayout(6,0));p.setBorder(new EmptyBorder(8,7,8,7));JLabel n=label(name,10,WHITE,Font.BOLD);JLabel v=label("+"+compact(xp)+" XP",9,GREEN,Font.BOLD);v.setHorizontalAlignment(SwingConstants.RIGHT);v.setPreferredSize(new Dimension(54,18));v.setMinimumSize(new Dimension(50,18));p.add(n,BorderLayout.CENTER);p.add(v,BorderLayout.EAST);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,38));return p;}
 private JPanel eventCard(ChronicleStore.Event e){Color c=color(e.type);JPanel p=surface(new BorderLayout(6,0));p.setBorder(BorderFactory.createCompoundBorder(new MatteBorder(0,2,0,0,c),new EmptyBorder(8,6,8,6)));JLabel art=new JLabel();art.setHorizontalAlignment(SwingConstants.CENTER);art.setPreferredSize(new Dimension(36,36));if(e.itemId>0){try{AsyncBufferedImage img=items.getImage(e.itemId,Math.max(1,e.quantity),e.quantity>1);img.addTo(art);}catch(Exception ignored){art.setText(symbol(e.type));}}else if("BOSS_KILL".equals(e.type)||"KILL".equals(e.type)){art=portrait(e.title,"BOSS_KILL".equals(e.type));}else{art.setText(symbol(e.type));art.setForeground(c);art.setFont(ui(Font.BOLD,20));}p.add(art,BorderLayout.WEST);JPanel mid=new JPanel();mid.setLayout(new BoxLayout(mid,BoxLayout.Y_AXIS));mid.setOpaque(false);String kicker=kicker(e);if(!kicker.isEmpty())mid.add(label(kicker,7,c,Font.BOLD));mid.add(label(e.title,11,WHITE,Font.BOLD));String d=e.detail==null?"":e.detail;if("LOOT".equals(e.type)){String qty=" ×"+Math.max(1,e.quantity);String src=e.source==null||e.source.isEmpty()?"":e.source+" · ";d=src+qty+" · GE "+RuneChroniclePlugin.gp(e.value)+" gp · HA "+RuneChroniclePlugin.gp(e.haValue)+" gp";}mid.add(label(trim(d,54),8,MUTED,Font.PLAIN));p.add(mid,BorderLayout.CENTER);p.add(label(Instant.ofEpochSecond(e.ts).atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("h:mm")),8,MUTED,Font.PLAIN),BorderLayout.EAST);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,70));p.setToolTipText(e.detail);return p;}
 private JLabel portrait(String name,boolean boss){String initial=(name==null||name.isEmpty())?"?":name.substring(0,1).toUpperCase(Locale.ROOT);JLabel l=new JLabel((boss?"♛ ":"")+initial,SwingConstants.CENTER);l.setOpaque(true);l.setBackground(boss?new Color(61,42,25):new Color(35,40,47));l.setForeground(boss?GOLD:RED);l.setFont(ui(Font.BOLD,boss?14:16));l.setPreferredSize(new Dimension(36,36));l.setBorder(BorderFactory.createLineBorder(boss?new Color(116,82,35):LINE));l.setToolTipText(name+" · loading authentic OSRS portrait");portraits.apply(name,l);return l;}
 private JPanel empty(){JPanel p=surface(new BorderLayout());JPanel q=new JPanel();q.setOpaque(false);q.setLayout(new BoxLayout(q,BoxLayout.Y_AXIS));q.add(label("Your story starts here",12,WHITE,Font.BOLD));q.add(label("Play normally — notable moments will appear automatically.",9,MUTED,Font.PLAIN));p.add(q);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,64));return p;}
 private static JPanel surface(LayoutManager l){JPanel p=new JPanel(l);p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(9,7,9,7)));return p;}
 private static JButton button(String s){JButton b=new JButton(s);b.setFocusable(false);b.setMargin(new Insets(2,5,2,5));b.setForeground(MUTED);b.setBackground(SURFACE);b.setBorder(BorderFactory.createLineBorder(LINE));return b;}
 private static JLabel label(String s,int z,Color c,int style){JLabel l=new JLabel(s);l.setForeground(c);l.setFont(ui(style,z));return l;}private static Font ui(int style,int z){return new Font("SansSerif",style,z);}private static String compact(long n){if(n>=1000000)return String.format(Locale.US,"%.2fM",n/1000000d);if(n>=1000)return String.format(Locale.US,"%.1fK",n/1000d);return String.format(Locale.US,"%,d",n);}private static String trim(String s,int n){return s.length()>n?s.substring(0,n-1)+"…":s;}private static Color color(String t){if("LOOT".equals(t))return GOLD;if("BOSS_KILL".equals(t))return GOLD;if("KILL".equals(t)||"DEATH".equals(t))return RED;if("LEVEL".equals(t))return GREEN;if("QUEST".equals(t)||"ACHIEVEMENT".equals(t))return PURPLE;if("PET".equals(t))return new Color(244,132,190);if("COLLECTION".equals(t))return CYAN;if("ACTIVITY".equals(t)||"CLUE".equals(t))return BLUE;return BLUE;}private static String symbol(String t){if("BOSS_KILL".equals(t))return"♛";if("KILL".equals(t))return"⚔";if("LEVEL".equals(t))return"↑";if("QUEST".equals(t))return"★";if("COLLECTION".equals(t))return"▣";if("PET".equals(t))return"♥";if("ACTIVITY".equals(t))return"◆";if("DEATH".equals(t))return"☠";return"•";}private static String kicker(ChronicleStore.Event e){if("BOSS_KILL".equals(e.type))return"BOSS DEFEATED";if("LOOT".equals(e.type))return e.category==null?"LOOT CLAIMED":e.category.toUpperCase(Locale.ROOT);if("PET".equals(e.type))return"RARE MOMENT";if("COLLECTION".equals(e.type))return"COLLECTION LOG";if("ACTIVITY".equals(e.type))return"ACTIVITY COMPLETE";if("PB".equals(e.type))return"PERSONAL BEST";return e.category==null?"":e.category.toUpperCase(Locale.ROOT);}
}
