package com.runechronicle;
import java.awt.*;import java.awt.image.BufferedImage;import java.io.File;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import javax.imageio.ImageIO;import javax.swing.*;import javax.swing.border.*;import net.runelite.client.util.AsyncBufferedImage;import net.runelite.client.game.ItemManager;
final class SessionRecapDialog{
 private static final Color BG=new Color(7,9,12),SURFACE=new Color(15,18,23),SURFACE2=new Color(21,25,31),LINE=new Color(46,52,61),GOLD=new Color(242,187,59),WHITE=new Color(244,246,249),MUTED=new Color(145,154,167),GREEN=new Color(81,207,133),RED=new Color(232,100,105),PURPLE=new Color(185,126,243);private final RuneChroniclePlugin plugin;private final ItemManager items;private final NpcPortraitService portraits;private RuneChroniclePlugin.Summary s;private final String player;private final boolean logoutPrompt;private final Runnable cont;private JDialog dialog;private JPanel capture,content;private String range="SESSION";private final Map<String,JButton> tabs=new LinkedHashMap<>();
 SessionRecapDialog(RuneChroniclePlugin p,String player,boolean logoutPrompt,Runnable cont){plugin=p;items=p.itemManager();portraits=p.npcPortraits();this.player=player;this.logoutPrompt=logoutPrompt;this.cont=cont;}
 void showDialog(){Window owner=KeyboardFocusManager.getCurrentKeyboardFocusManager().getActiveWindow();dialog=new JDialog(owner,"RuneChronicle — Recap",Dialog.ModalityType.APPLICATION_MODAL);dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);dialog.addWindowListener(new java.awt.event.WindowAdapter(){@Override public void windowClosed(java.awt.event.WindowEvent e){cont.run();}});dialog.getRootPane().registerKeyboardAction(e->dialog.dispose(),KeyStroke.getKeyStroke("ESCAPE"),JComponent.WHEN_IN_FOCUSED_WINDOW);capture=buildShell();JScrollPane sc=new JScrollPane(capture);sc.setBorder(null);sc.getViewport().setBackground(BG);sc.getVerticalScrollBar().setUnitIncrement(20);dialog.setContentPane(sc);dialog.setSize(780,680);dialog.setMinimumSize(new Dimension(660,540));dialog.setLocationRelativeTo(owner);selectRange("SESSION");dialog.setVisible(true);}
 private JPanel buildShell(){JPanel root=new JPanel();root.setLayout(new BoxLayout(root,BoxLayout.Y_AXIS));root.setBackground(BG);root.setBorder(new EmptyBorder(16,26,20,26));
  JPanel brand=new JPanel(new FlowLayout(FlowLayout.CENTER,0,0));brand.setOpaque(false);brand.add(t("RUNE",11,WHITE,Font.BOLD));brand.add(t("CHRONICLE",11,GOLD,Font.BOLD));root.add(brand);
  JLabel title=t(logoutPrompt?"BEFORE YOU GO":"YOUR CHRONICLE",26,WHITE,Font.BOLD);title.setAlignmentX(.5f);root.add(title);
  JLabel sub=t(player+"  ·  "+LocalDateTime.now().format(DateTimeFormatter.ofPattern("EEEE, MMM d · h:mm a")),10,MUTED,Font.PLAIN);sub.setAlignmentX(.5f);root.add(sub);root.add(Box.createVerticalStrut(12));
  JPanel tabBar=new JPanel(new GridLayout(1,5,6,0));tabBar.setOpaque(false);for(String x:new String[]{"SESSION","TODAY","WEEK","MONTH","CUSTOM"}){JButton b=button(x,SURFACE,WHITE);b.setPreferredSize(new Dimension(100,34));b.addActionListener(e->selectRange(x));tabs.put(x,b);tabBar.add(b);}tabBar.setMaximumSize(new Dimension(680,34));tabBar.setAlignmentX(.5f);root.add(tabBar);root.add(Box.createVerticalStrut(12));
  content=new JPanel();content.setLayout(new BoxLayout(content,BoxLayout.Y_AXIS));content.setOpaque(false);content.setAlignmentX(.5f);content.setMaximumSize(new Dimension(680,Integer.MAX_VALUE));root.add(content);return root;}
 private void selectRange(String next){if("CUSTOM".equals(next)){if(!chooseCustomRange())return;}else{s=plugin.summary(next);}range=next;for(Map.Entry<String,JButton> e:tabs.entrySet()){boolean on=e.getKey().equals(range);e.getValue().setBackground(on?new Color(52,42,22):SURFACE);e.getValue().setForeground(on?GOLD:MUTED);e.getValue().setBorder(BorderFactory.createLineBorder(on?new Color(121,94,38):LINE));}renderContent();}
 private boolean chooseCustomRange(){JSpinner from=new JSpinner(new SpinnerDateModel()),to=new JSpinner(new SpinnerDateModel());from.setEditor(new JSpinner.DateEditor(from,"MMM d, yyyy"));to.setEditor(new JSpinner.DateEditor(to,"MMM d, yyyy"));java.util.Date now=new java.util.Date();from.setValue(java.util.Date.from(Instant.now().minusSeconds(7*86400L)));to.setValue(now);JPanel p=new JPanel(new GridLayout(2,2,8,8));p.add(new JLabel("From"));p.add(from);p.add(new JLabel("To"));p.add(to);if(JOptionPane.showConfirmDialog(dialog,p,"Custom Chronicle",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return false;long a=((java.util.Date)from.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate().atStartOfDay(ZoneId.systemDefault()).toEpochSecond();long b=((java.util.Date)to.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate().plusDays(1).atStartOfDay(ZoneId.systemDefault()).toEpochSecond()-1;if(b<a){long x=a;a=b;b=x;}s=plugin.summary(a,b);return true;}
 private void renderContent(){content.removeAll();String heading="SESSION".equals(range)?"SESSION RECAP":("CUSTOM".equals(range)?"CUSTOM CHRONICLE":range+"'S CHRONICLE");JLabel h=t(heading,12,GOLD,Font.BOLD);h.setAlignmentX(.5f);content.add(h);content.add(Box.createVerticalStrut(8));
  ChronicleStore.Event hero=bestMoment();if(hero!=null){JPanel hp=hero(hero);hp.setMaximumSize(new Dimension(Integer.MAX_VALUE,116));content.add(hp);content.add(Box.createVerticalStrut(10));}
  JPanel m=new JPanel(new GridLayout(2,3,7,7));m.setOpaque(false);m.add(metric("PLAYED",RuneChroniclePlugin.format(s.playSeconds),WHITE));m.add(metric("XP EARNED",compact(s.xp)+" XP",GREEN));m.add(metric("LEVELS GAINED",compact(s.levels),GREEN));m.add(metric("BOSSES",compact(s.bossKills),GOLD));m.add(metric("KILLS",compact(s.kills),WHITE));m.add(metric("LOOT VALUE",RuneChroniclePlugin.gp(s.lootValue)+" gp",GOLD));m.setMaximumSize(new Dimension(Integer.MAX_VALUE,159));content.add(m);
  if(!s.bossCounts.isEmpty()){content.add(section("BOSSES DEFEATED"));JPanel bosses=new JPanel(new GridLayout(0,3,7,7));bosses.setOpaque(false);s.bossCounts.entrySet().stream().sorted((a,b)->Long.compare(b.getValue(),a.getValue())).limit(6).forEach(e->bosses.add(bossTile(e.getKey(),e.getValue())));bosses.setMaximumSize(new Dimension(Integer.MAX_VALUE,((Math.min(6,s.bossCounts.size())+2)/3)*70));content.add(bosses);}
  java.util.List<ChronicleStore.Event> high=groupHighlights(s.events);content.add(section("ADVENTURE HIGHLIGHTS"));if(high.isEmpty())content.add(note("No major journal moments in this "+range.toLowerCase(Locale.ROOT)+" yet."));else{for(ChronicleStore.Event e:high.subList(0,Math.min(7,high.size())))content.add(eventRow(e));}
  if(!s.skillXp.isEmpty()){content.add(section("PROGRESS"));s.skillXp.entrySet().stream().sorted((a,b)->Long.compare(b.getValue(),a.getValue())).limit(8).forEach(e->content.add(progress(e.getKey(),e.getValue())));}
  content.add(Box.createVerticalStrut(14));JPanel a=new JPanel(new GridLayout(1,2,9,0));a.setOpaque(false);JButton save=button("SAVE SHARE CARD",SURFACE,WHITE);save.addActionListener(e->save(save));a.add(save);JButton close=button(logoutPrompt?"CONTINUE PLAYING":"CLOSE RECAP",logoutPrompt?GOLD:SURFACE,logoutPrompt?new Color(18,18,18):WHITE);close.addActionListener(e->dialog.dispose());a.add(close);a.setMaximumSize(new Dimension(Integer.MAX_VALUE,42));content.add(a);
  if(logoutPrompt){JLabel hint=t("To log out, close this recap and click RuneScape's red logout button again.",9,MUTED,Font.PLAIN);hint.setAlignmentX(.5f);hint.setBorder(new EmptyBorder(10,0,0,0));content.add(hint);}JLabel foot=t("RuneChronicle · Your adventure, remembered",9,MUTED,Font.PLAIN);foot.setAlignmentX(.5f);foot.setBorder(new EmptyBorder(10,0,0,0));content.add(foot);content.revalidate();content.repaint();if(dialog!=null)SwingUtilities.invokeLater(()->dialog.repaint());}
 private java.util.List<ChronicleStore.Event> groupHighlights(java.util.List<ChronicleStore.Event> events){
  java.util.List<ChronicleStore.Event> reversed=new ArrayList<>();for(ChronicleStore.Event e:events)if(!"XP".equals(e.type)&&!"SESSION_START".equals(e.type)&&!"SESSION_END".equals(e.type)&&!"BOSS_KILL".equals(e.type))reversed.add(e);Collections.reverse(reversed);
  java.util.List<ChronicleStore.Event> out=new ArrayList<>();java.util.Map<String,ChronicleStore.Event> ordinary=new LinkedHashMap<>();
  for(ChronicleStore.Event e:reversed){boolean group="KILL".equals(e.type)||"LOOT".equals(e.type);if(!group){out.add(e);continue;}String key=e.type+"|"+e.title+"|"+(e.source==null?"":e.source);ChronicleStore.Event g=ordinary.get(key);if(g==null){g=new ChronicleStore.Event(e.ts,e.profileId,e.sessionId,e.type,e.title,e.detail,e.amount,e.source,e.value,e.itemId,e.quantity);g.haValue=e.haValue;g.category=e.category;ordinary.put(key,g);out.add(g);}else{g.amount+=e.amount;g.value+=e.value;g.haValue+=e.haValue;g.quantity+=e.quantity;if("KILL".equals(g.type))g.detail="Defeated ×"+g.amount;}}
  return out;
 }
 private ChronicleStore.Event bestMoment(){ChronicleStore.Event best=null;long score=-1;for(ChronicleStore.Event e:s.events){long x=0;if("PET".equals(e.type))x=100000000000L;else if("COLLECTION".equals(e.type))x=90000000000L;else if("LOOT".equals(e.type))x=1000000000L+e.value;else if("PB".equals(e.type))x=800000000L;else if("QUEST".equals(e.type)||"ACHIEVEMENT".equals(e.type))x=700000000L;else if("BOSS_KILL".equals(e.type))x=500000000L;if(x>score){score=x;best=e;}}return best;}
 private JPanel hero(ChronicleStore.Event e){JPanel p=new JPanel(new BorderLayout(18,0));p.setBackground(new Color(28,23,15));p.setBorder(BorderFactory.createCompoundBorder(new MatteBorder(1,1,1,1,new Color(111,84,31)),new EmptyBorder(16,18,16,18)));JLabel art=art(e,72);p.add(art,BorderLayout.WEST);JPanel q=new JPanel();q.setOpaque(false);q.setLayout(new BoxLayout(q,BoxLayout.Y_AXIS));q.add(t(heroKicker(e),9,GOLD,Font.BOLD));q.add(t(e.title,23,WHITE,Font.BOLD));q.add(t(heroDetail(e),11,MUTED,Font.PLAIN));p.add(q,BorderLayout.CENTER);return p;}
 private JPanel metric(String k,String v,Color c){JPanel p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(new MatteBorder(2,0,0,0,c),new EmptyBorder(10,7,10,7)));JLabel a=t(k,8,MUTED,Font.BOLD),b=t(v,15,WHITE,Font.BOLD);a.setAlignmentX(.5f);b.setAlignmentX(.5f);p.add(a);p.add(Box.createVerticalStrut(4));p.add(b);return p;}
 private JPanel bossTile(String n,long c){JPanel p=new JPanel(new BorderLayout(8,0));p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(9,10,9,10)));JLabel a=new JLabel("♛",SwingConstants.CENTER);a.setForeground(GOLD);a.setFont(ui(Font.BOLD,18));a.setPreferredSize(new Dimension(36,36));portraits.apply(n,a,36);p.add(a,BorderLayout.WEST);JPanel x=new JPanel();x.setOpaque(false);x.setLayout(new BoxLayout(x,BoxLayout.Y_AXIS));x.add(t(n,10,WHITE,Font.BOLD));x.add(t("×"+c,10,GOLD,Font.BOLD));p.add(x);return p;}
 private JLabel section(String x){JLabel l=t(x,9,GOLD,Font.BOLD);l.setBorder(new EmptyBorder(22,1,7,1));return l;}
 private JPanel eventRow(ChronicleStore.Event e){JPanel p=new JPanel(new BorderLayout(11,0));p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(2,0,2,0),BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(9,11,9,11))));p.add(art(e,40),BorderLayout.WEST);JPanel q=new JPanel();q.setOpaque(false);q.setLayout(new BoxLayout(q,BoxLayout.Y_AXIS));q.add(t(kicker(e),7,color(e.type),Font.BOLD));q.add(t(e.title,11,WHITE,Font.BOLD));q.add(t(shortDetail(e),9,MUTED,Font.PLAIN));p.add(q,BorderLayout.CENTER);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,66));return p;}
 private JLabel art(ChronicleStore.Event e,int size){JLabel l=new JLabel("",SwingConstants.CENTER);l.setPreferredSize(new Dimension(size,size));if(e.itemId>0){try{AsyncBufferedImage im=items.getImage(e.itemId,Math.max(1,e.quantity),e.quantity>1);im.addTo(l);}catch(Exception ignored){l.setText(symbol(e.type));}}else if("BOSS_KILL".equals(e.type)||"KILL".equals(e.type)){l.setText(symbol(e.type));l.setForeground(color(e.type));l.setFont(ui(Font.BOLD,Math.max(18,size/2)));portraits.apply(e.title,l,size);}else{l.setText(symbol(e.type));l.setForeground(color(e.type));l.setFont(ui(Font.BOLD,Math.max(18,size/2)));}return l;}
 private JPanel progress(String a,long xp){JPanel p=new JPanel(new BorderLayout());p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(2,0,2,0),BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(9,12,9,12))));p.add(t(a,10,WHITE,Font.BOLD),BorderLayout.WEST);p.add(t("+"+compact(xp)+" XP",10,GREEN,Font.BOLD),BorderLayout.EAST);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,42));return p;}
 private JPanel note(String x){JPanel p=new JPanel(new BorderLayout());p.setBackground(SURFACE);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LINE),new EmptyBorder(14,12,14,12)));p.add(t(x,10,MUTED,Font.PLAIN));p.setMaximumSize(new Dimension(Integer.MAX_VALUE,62));return p;}
 private static JLabel t(String s,int z,Color c,int st){JLabel l=new JLabel(s);l.setForeground(c);l.setFont(ui(st,z));return l;}private static Font ui(int st,int z){return new Font("SansSerif",st,z);}private static JButton button(String x,Color b,Color f){JButton z=new JButton(x);z.setFocusable(false);z.setBackground(b);z.setForeground(f);z.setFont(ui(Font.BOLD,10));z.setBorder(BorderFactory.createLineBorder(b==GOLD?GOLD:LINE));return z;}private static String compact(long n){if(n>=1000000)return String.format(Locale.US,"%.2fM",n/1000000d);if(n>=1000)return String.format(Locale.US,"%.1fK",n/1000d);return String.format(Locale.US,"%,d",n);}private static String symbol(String t){if("LOOT".equals(t))return"◆";if("BOSS_KILL".equals(t))return"♛";if("KILL".equals(t))return"⚔";if("LEVEL".equals(t))return"↑";if("QUEST".equals(t))return"★";if("COLLECTION".equals(t))return"▣";if("PET".equals(t))return"♥";if("DEATH".equals(t))return"☠";return"•";}private static Color color(String t){if("LOOT".equals(t)||"BOSS_KILL".equals(t))return GOLD;if("PET".equals(t))return new Color(244,132,190);if("COLLECTION".equals(t))return new Color(91,198,207);if("QUEST".equals(t)||"ACHIEVEMENT".equals(t))return PURPLE;if("KILL".equals(t)||"DEATH".equals(t))return RED;return new Color(91,158,238);}private static String kicker(ChronicleStore.Event e){if("LOOT".equals(e.type))return"LOOT OBTAINED";if("PET".equals(e.type))return"NEW PET";if("COLLECTION".equals(e.type))return"COLLECTION LOG UNLOCK";if("ACTIVITY".equals(e.type))return"ACTIVITY COMPLETE";if("PB".equals(e.type))return"NEW PERSONAL BEST";return e.category==null?e.type:e.category.toUpperCase(Locale.ROOT);}private static String shortDetail(ChronicleStore.Event e){if("LOOT".equals(e.type))return (e.source==null?"":e.source+" · ")+"×"+Math.max(1,e.quantity)+" · "+RuneChroniclePlugin.gp(e.value)+" gp GE · "+RuneChroniclePlugin.gp(e.haValue)+" gp HA";return e.detail==null?"":e.detail;}private static String heroKicker(ChronicleStore.Event e){if("PET".equals(e.type))return"★ RAREST MOMENT · NEW PET";if("COLLECTION".equals(e.type))return"★ NEW COLLECTION LOG SLOT";if("LOOT".equals(e.type))return"★ BEST DROP · "+RuneChroniclePlugin.gp(e.value)+" GP";if("PB".equals(e.type))return"★ NEW PERSONAL BEST";if("BOSS_KILL".equals(e.type))return"★ BOSS DEFEATED";return"★ SESSION HIGHLIGHT";}private static String heroDetail(ChronicleStore.Event e){if("LOOT".equals(e.type))return (e.source==null?"":e.source+" · ")+e.detail;return e.detail==null?"A moment worth remembering.":e.detail;}
 private void save(JButton b){try{File d=new File(System.getProperty("user.home"),"RuneLite/screenshots/RuneChronicle");d.mkdirs();File o=new File(d,"RuneChronicle_"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss"))+".png");Dimension old=capture.getSize();capture.setSize(Math.max(720,capture.getPreferredSize().width),capture.getPreferredSize().height);capture.doLayout();BufferedImage im=new BufferedImage(capture.getWidth(),capture.getHeight(),BufferedImage.TYPE_INT_ARGB);Graphics2D g=im.createGraphics();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);capture.printAll(g);g.dispose();capture.setSize(old);ImageIO.write(im,"png",o);b.setText("SAVED ✓");b.setToolTipText(o.getAbsolutePath());}catch(Exception ex){b.setText("SAVE FAILED");}}
}
